### ISSUE TITLE
PE-D Issues

### ISSUE THREAD

**Issue by ivantjh** [AY2021S2-CS2103T-W14-1/tp#205]
## Groups

- [x] #159 - typo in "Add-group" cmd (@Assyarul )
- [x] #162 - Clicking on rows creates a blue highlight which hinders viewing (just add some other more visible indicator, don't use javafx, duplicate of #129) (@Assyarul)
- [x] #182 - UG and Application for del-group is not updated (Fixed in v1.3.1, closed)
- [x] #183 - del-group command is unknown (Fixed in v1.3.1, closed)
- [x] #196 - Unclear success command for add-group (@Assyarul )
- [x] #199 - The person inside my “abc” group went missing for `add-debt` (can't repro)
- [x] #200 - The person inside my “abc” group went missing for `del-date` (can't repro)
- [x] #201 - The person inside my “abc” group went missing for `add-date` (can't repro)
- [x] #202 - Always returning back to the original list (after adding a meeting, date, debt, I think this is intended) (@chesterhow)
- [x] #203 - del-group command not working (Fixed in v1.3.1, closed)

## Person

- [x] #155 - What makes a friend unique? (Can be fixed by creating a Person section in UG) (@ivantjh)
- [x] #156 - Profile pictures that may have been moved/renamed/deleted from the data folder cause the app to delete ALL data 
- [x] #160 - Email field allows invalid email addresses
- [x] #161 - Email field vulnerable to string injection 
- [x] #173 - Some details of friend are not unique (Unique friends again :cries) (@ivantjh)
- [x] #176 - Some details of Edit function should be unique (Unique friends wow) (@ivantjh)
- [x] #177 - Add invalid name (damm numbers as name) (@ivantjh)
- [x] #179 - Name of person not case sensitive (validation issues) (@ivantjh)
- [x] #190 - Able to edit name of person to same name as another person but different case (@ivantjh)

## Birthday for Person

- [x] #178 - Able to add invalid birthdate (Able to add a birthdate of a person past the current date) (@ivantjh)
- [x] #189 - Able to edit birthdate past current date (@ivantjh)
- [x] #193 - Birthday accepting an invalid date (invalid issue, wrong leap day given, closed) (@ivantjh)

## Debts

- [x] #153, #172, #185, #195 - negative debt (Can be fixed by creating a Person section in UG)
- [x] #181 - Add-debt unable to add certain numbers (@Assyarul )

## Images

- [x] #151 - resized img not centred (@chesterhow)
- [x] #154 - UG does not specify acceptable file formats for images (@ivantjh)
- [x] #184 - Bug to do with Add-picture in application that messes up the UI (update docs to tell them not to edit pictures directly in /data folder, @chesterhow)

## Meetings

- [x] #152 - Meeting dates in the future are allowed
- [x] #165 - Error message with invalid date when adding meeting shows format specifiers
- [x] #168 - Meetings should be listed in chronological order (Simple)
- [x] #170 - Entered example codes specified in UG but doesn't work (fix UG examples) (@ivantjh)
- [x] #188 - add-meeting does not work as intended (the guy testing is using v1.3 of app, maybe it is an error with a single meeting etc)
- [x] #191 - Able to add invalid meeting dates (able to add meeting before the guy is born) (@ivantjh)
- [x] #197 - Weird looking error message for add-meeting (Format specifier, same as #165)

## Special Dates

- [x] #158 - Dates that happen more than a year in the future still show up within the scope of the current year (Need to update docs for special dates, just say anniversary, @ivantjh)
- [x] #174 - Upcoming event panel ambiguity (Just say anniversary, @chesterhow)
- [x] #180 - Description for add-date can be ambiguous
- [x] #198 - Error message doesn’t match my invalid input for `del-date` (@chesterhow)

## Goals/streak

- [x] #149 - Deadline for yearly goal is incorrect (intended, update docs, closed)
- [x] #150 - goal issue
- [x] #166 - Deadline for goals do not update after adding latest meeting goal (intended, update docs, closed)
- [x] #167 - Deadline for weekly goal is incorrect based on added meeting (intended, updated docs, closed)
- [x] #171 - `set-goal` Feature description doesn't seem to match (Intended, just update docs, closed)
- [x] #204 - `set-goal` feature (suggestion on not having the feature, can't do much now, issue closed)

## Find

- [x] #175 - Unclear example in find function (update docs for regex search)

## Autocomplete

- [ ] #157 - Autocomplete for commands that have been fully typed require 2 presses of enter (probably can't fix)
- [x] #187 - No autocomplete for some commands such as set-goal (Fixed in v1.3.1, closed)

## Aesthetics

- [x] #163 - Purpose of clicking and colour highlight is not documented (disable all clicking) (@Assyarul)
- [x] #164 - Long names do not cause text wrap and they disappear into the side (for result display, person list card) (@chesterhow)
- [x] #186 - Clearing address book does not clear events (Duplicate of #117, @chesterhow)
- [x] #192 - Default Font does not work with Mac OS Big Sur (Unable to reproduce, closed)
- [x] #194 - Unable to differentiate add command error and add-date command error (Nope, we can't fix this because the app will detect `add`)

## UG

- [x] #169 - Grammar issues in UG under "Where to get additional help" (@ivantjh)
